return {
	--  {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	tag = "0.1.8",
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 		{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
	--
	-- 		"nvim-telescope/telescope-smart-history.nvim",
	-- 		"nvim-telescope/telescope-ui-select.nvim",
	-- 	},
	-- 	keys = {
	-- 		{ "<leader>/", false },
	-- 		{ "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
	-- 		{ "<leader>ft", "<cmd>Telescope git_files<cr>", desc = "Find Git files" },
	-- 		{ "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Find Files" },
	-- 		{ "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Live Grep" },
	-- 		{ "<leader>fc", "<cmd>Telescope colorscheme<cr>", desc = "Change Colorscheme" },
	-- 		{
	-- 			"<leader>fp",
	-- 			function()
	-- 				require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root })
	-- 			end,
	-- 			desc = "Find Plugin File",
	-- 		},
	-- 		{ "<space>/", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Find Current Buffer" },
	-- 	},
	-- 	opts = {
	-- 		pickers = {
	-- 			colorscheme = {
	-- 				enable_preview = true,
	-- 			},
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"nvim-telescope/telescope-ui-select.nvim",
	-- 	config = function()
	-- 		require("telescope").setup({
	-- 			extensions = {
	-- 				["ui-select"] = {
	-- 					require("telescope.themes").get_dropdown({
	-- 						-- even more opts
	-- 					}),
	-- 				},
	-- 			},
	-- 		})
	-- 		require("telescope").load_extension("ui-select")
	-- 	end,
	-- },
}
